apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-user
  namespace: reto5
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: reto5
  name: api-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: reto5
subjects:
  - kind: ServiceAccount
    name: api-user
    namespace: reto5
roleRef:
  kind: Role
  name: api-reader
  apiGroup: rbac.authorization.k8s.io
